import discord
from discord.ext import commands
from utils import *
from discord.ext import tasks
import aiohttp
import json

class Isles(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
    
    @commands.command(name="skill", description="Displays a skill of the user", aliases=["s", "sk"])
    async def skill(self, ctx, skill = "Provide arg or else ur mom"):
        if ctx.author.id not in [667760867483582492]: return await ctx.reply("ur mom OHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHHHOOHOHOHOHOOHOHOHOHOOHOHOHOHOHOHOOHOHOHOHOHOOHOHOHOOHOHHH")
        w = skill
        skill = aliases(skill)
        if skill == None: return await ctx.reply(f"There was no skill called `{w}`. Please try again.")
        embed = discord.Embed(title=f"**MetaGG2's {Strings.Capitalize(skill)} Stats**", description=f"XP: **{Get.XP(skill)}**\nXP-NL: **{Get.XPNL(skill)}**\nRank: **#{await Get.Rank(skill)}**")

        embed.add_field(name=f"**Progress ({Get.Progress(skill)}%)**", value=Get.ProgressBar(skill), inline=False)
        embed.set_thumbnail(url=Get.Image(skill))
        embed.set_footer(text="Coutesy of Wavey#0309", icon_url=ctx.author.avatar_url)

        await ctx.send(embed=embed)


    @tasks.loop(seconds=60.0)
    async def data():
            async with aiohttp.ClientSession() as session:
                async with session.get("https://api.skyblockisles.com/player/MetaGG2") as resp:
                    with open('data.json', 'r+') as f:
                        json.dump(await resp.json(), f)

    data.start()

def setup(bot):
    bot.add_cog(Isles(bot))